### PR TITLE
fix: fix withSetsNumericTraits null issue

### LINKED ISSUE #101: [Subgraph] WithSetsNumericTraits is null
We have an issue with the Subgraph.
Right now some aavegotchis have the field withSetsNumericTraits is null.
This shouldnt be the case and should be the case.

``` 
{aavegotchis(where:{withSetsNumericTraits:null}) {
  id
  modifiedNumericTraits
  withSetsNumericTraits
}}
```

results in 

```
{
  "data": {
    "aavegotchis": [
      {
        "id": "14792",
        "modifiedNumericTraits": [
          79,
          22,
          2,
          3,
          53,
          71
        ],
        "withSetsNumericTraits": null
      },
      {
        "id": "1674",
        "modifiedNumericTraits": [
          77,
          8,
          8,
          32,
          85,
          11
        ],
        "withSetsNumericTraits": null
      },
      {
        "id": "20427",
        "modifiedNumericTraits": [
          44,
          56,
          20,
          29,
          78,
          50
        ],
        "withSetsNumericTraits": null
      }
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by orionstardust**
Fix #101

### CODE REVIEW

File: src/utils/helpers/diamond.ts [hunk 1]
```diff
@@ -80,6 +81,12 @@ export function getOrCreateAavegotchi(
         gotchi.historicalPrices = [];
         gotchi.kinship = BigInt.fromI32(50);
         gotchi.withSetsRarityScore = BIGINT_ZERO;
+        gotchi = updateAavegotchiInfo(
```
Comment (cinnabarhorse) [inline src/utils/helpers/diamond.ts:84]: Is this function call absolutely necessary? @orionstardust
